# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module platyPS -Force -Confirm:$false -Scope CurrentUser'
    pwsh: true
  displayName: 'Install platyPS'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module PowerShellGet -Force -Confirm:$false -Scope CurrentUser'
    pwsh: true
  displayName: 'Install PowerShellGet [v2.1.3 has a Publish-Module bug]'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: 'build.proj /t:Build;GenerateHelp /p:Configuration=Release'
  displayName: 'Build'